package exception

func (e *exception) GeneralInternalErrorMsg() string {
	return "Maaf, terjadi kesalahan saat memproses data Anda. Silakan coba lagi nanti atau hubungi tim dukungan jika masalah masih berlanjut."
}
